version: "3.9"

services:
  postgresql:
    image: postgres:latest
    container_name: jschat-app-postgredb
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - ./postgres-initapp.sql:/docker-entrypoint-initdb.d/postgres-initapp.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  jshat-server:
    container_name: jschat-app-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgresql:
        condition: service_healthy
